12 edit competency
OpenSkool/OpenSkool pull request #110
Opened 2022-03-28 14:55 UTC by SiteSeerBE

2022-03-28 16:45 UTC, Moeriki requested changes

2022-03-28 16:45 UTC, Moeriki commented on app/src/generated/components.d.ts
Enkel de change op lijn 14 is hier relevant.

2022-03-28 16:45 UTC, Moeriki commented on app/src/pages/manage/competencies/index.vue
> +        :to="`/manage/competencies/${competency?.id}/edit`"
Optional chaining zou hier niet nodig moeten zijn.

2022-03-28 16:45 UTC, Moeriki commented on app/src/pages/manage/competencies/index.vue
>        {{ competency?.title }}
Je mag de optional chain hier ook weghalen.

2022-03-28 16:45 UTC, Moeriki commented on app/src/pages/manage/competencies/[id]/edit.vue
> +    <li>{{ result?.rootCompetency?.title }}</li>
Deze entry rendert volgens mij `undefined` in plain text in de UI wnn de result nog niet geladen is.

Moeten we niet perse nu oplossen maar dus de ganse pagina moet wel effectief suspended zijn tot de data geladen.

2022-03-29 08:12 UTC, SiteSeerBE commented on app/src/generated/components.d.ts
Fixed

2022-03-29 08:12 UTC, SiteSeerBE commented on app/src/pages/manage/competencies/index.vue
>        {{ competency?.title }}
Volgens TS kan result undefined zijn.

2022-03-29 08:12 UTC, SiteSeerBE commented on app/src/pages/manage/competencies/index.vue
> +        :to="`/manage/competencies/${competency?.id}/edit`"
Done

2022-03-29 08:13 UTC, Moeriki approved these changes

2022-03-29 08:17 UTC, merged