✅ refactor and add tests
OpenSkool/OpenSkool pull request #138
Opened 2022-04-11 13:36 UTC by SiteSeerBE

2022-04-11 13:42 UTC, Moeriki requested changes

2022-04-11 13:42 UTC, Moeriki commented on app/src/pages/manage/competencies/[id]/edit.spec.ts
> +import 'virtual:windi.css';
Waarom de CSS?

2022-04-11 13:42 UTC, Moeriki commented on app/src/pages/manage/competencies/[id]/edit.spec.ts
> +import { router } from '~/router';
Mag grouped by lijn 5.

2022-04-11 13:42 UTC, Moeriki commented on app/src/pages/manage/competencies/[id]/index.spec.ts
> +test.only('delete competency works', async () => {
`.only` moet weg.

2022-04-11 13:42 UTC, Moeriki commented on app/src/spec/render.ts
> +  return { ...utils };
Spread doet niets funcitoneel. `return utils` is identiek.

2022-04-11 13:42 UTC, Moeriki commented on app/src/spec/render.ts
> +function render(component: any): RenderResult {
`export function render` ipv lijn 26 apart.

2022-04-13 13:06 UTC, SiteSeerBE commented on app/src/pages/manage/competencies/[id]/edit.spec.ts
> +import 'virtual:windi.css';
Dan kan de virtual-DOM ook naar het mooie design kijken.

2022-04-13 13:07 UTC, SiteSeerBE commented on app/src/pages/manage/competencies/[id]/index.spec.ts
> +test.only('delete competency works', async () => {
Vergeten te verwijderen, verdorie.

2022-04-13 13:09 UTC, SiteSeerBE commented on app/src/spec/render.ts
> +  return { ...utils };
Done

2022-04-13 13:09 UTC, SiteSeerBE commented on app/src/spec/render.ts
> +function render(component: any): RenderResult {
Done

2022-04-13 13:16 UTC, Moeriki approved these changes

2022-04-13 14:18 UTC, Moeriki approved these changes

2022-04-13 14:18 UTC, merged