109 frameworks
OpenSkool/OpenSkool pull request #149
Opened 2022-04-20 14:34 UTC by SiteSeerBE

- Lots of changes to bring competencies into frameworks.
- Several test scripts still have to be refactored.
Ref: #109

2022-04-20 14:41 UTC, SiteSeerBE commented
Volgens testing kan competencyFramework null zijn. Kunnen we dat non-nullable maken?

2022-04-20 14:58 UTC, shkurata approved these changes
:+1:

2022-04-20 15:06 UTC, Moeriki commented
FYI Ik wacht met review tot de testen slagen.

2022-04-20 16:08 UTC, SiteSeerBE commented
> FYI Ik wacht met review tot de testen slagen.

Noted & Resolved.

Sorry van de 💩. Ik had eerst gewoon een assert toegevoegd, maar dacht dan net voor het comitten aan een betere oplossing.

2022-04-21 06:25 UTC, Moeriki requested changes
A handful of tests were deleted. Was this intentional?

2022-04-21 06:25 UTC, Moeriki commented on app/src/pages/manage/frameworks/[frameworkId]/[competencyId]/index.vue
> +  frameworkId: string;
Inconsistent usage of `// route param`. I don't mind if you keep using it or not. Remove everywhere or add everywhere relevant.

2022-04-22 06:15 UTC, SiteSeerBE commented on app/src/pages/manage/frameworks/[frameworkId]/[competencyId]/index.vue
> +  frameworkId: string;
Removed everywhere.

2022-04-22 07:01 UTC, Moeriki approved these changes

2022-04-22 07:28 UTC, SiteSeerBE commented
> A handful of tests were deleted. Was this intentional?

Yes, although it was intentional, I now see they weren't that hard to refactor to the new structure. Some I just had to move in another folder :)

2022-04-22 09:06 UTC, Moeriki approved these changes

2022-04-22 09:22 UTC, merged