Feat/integration tests
OpenSkool/OpenSkool pull request #161
Opened 2022-04-21 12:54 UTC by shkurata

2022-04-21 13:53 UTC, Moeriki requested changes

2022-04-21 13:53 UTC, Moeriki commented on api/test/competency-mutations.spec.ts
> +
You can write helpers for testing but don't do assertions (`expect`) in a helper. This obfuscates what a test is actually testing. Developer shouldn't have to click around for that.

DRY is not so important for tests. Tests should very clearly contain all steps.

We could gather some common queries, or make helpers to fetch certain types of data. But I would honestly not even do that.

2022-04-21 13:53 UTC, Moeriki commented on api/test/competency-queries.spec.ts
> +
Why was this refactored?

2022-04-21 14:00 UTC, shkurata commented on api/test/competency-queries.spec.ts
> +
I first wanted to reuse the query to fetch the competence by id and I made a function that can be exported and then I saw that the same query was used in almost all tests, so I replaced the queries with the function. Then I realised that this query will not be of use in my tests, but I left the function to be reviewed.

2022-04-21 14:08 UTC, Moeriki commented on api/test/competency-queries.spec.ts
> +
Ok. The same remarks as the other file apply here.

2022-04-22 09:00 UTC, Moeriki approved these changes

2022-04-22 11:10 UTC, SiteSeerBE approved these changes

2022-04-22 11:12 UTC, merged