11 reorder competencies
OpenSkool/OpenSkool pull request #163
Opened 2022-04-25 12:00 UTC by SiteSeerBE

2022-04-25 13:02 UTC, Moeriki requested changes

2022-04-25 13:02 UTC, Moeriki commented on app/src/components/list/competency-list.vue
> +      }
Hier moet nog error handling bij.

2022-04-26 08:34 UTC, SiteSeerBE commented on app/src/components/list/competency-list.vue
> +      }
Done

2022-04-26 08:39 UTC, Moeriki approved these changes

2022-04-26 08:44 UTC, merged