🥅  add `AppNotFound` error to all `ID` operations
OpenSkool/OpenSkool pull request #176
Opened 2022-04-27 11:41 UTC by shkurata

The error is added to all `competency` operations.

2022-04-27 11:47 UTC, SiteSeerBE approved these changes

2022-04-27 12:07 UTC, Moeriki requested changes

2022-04-27 12:07 UTC, Moeriki commented on api/test/competency-mutations.spec.ts
> +  });
Title says "error on framework not found" but implementation checks title.

2022-04-27 12:07 UTC, Moeriki commented on api/test/competency-mutations.spec.ts
> +
Title says "error on framework not found" but implementation checks title.

2022-04-27 12:07 UTC, Moeriki commented on api/test/competency-queries.spec.ts
> +          }
The helper is named `getCompetencyForIdAndLocale`. I wouldn't expect it to return an error.

We really only want helpers that are lean and mean. If they handle different cases for different tests, something is wrong.

For the error cases I would stick to fetching them within the test or create a helper that specifically fetches user errors.

2022-04-27 12:07 UTC, Moeriki commented on api/test/competency-queries.spec.ts
> +          }
The helper is named `getCompetencyFrameworkForIdAndLocale`. I wouldn't expect it to return an error.

We really only want helpers that are lean and mean. If they handle different cases for different tests, something is wrong.

For the error cases I would stick to fetching them within the test or create a helper that specifically fetches user errors.

2022-04-27 12:08 UTC, Moeriki commented
The App graphql is not updated which seems improbably with such heavy API changes. Make sure to generate `yarn generate` to be sure. I expect there might also be type errors in the App as a result since it depends on the Api design.

2022-04-27 12:42 UTC, Moeriki requested changes

2022-04-27 12:42 UTC, Moeriki commented on api/test/competency-queries.spec.ts
> +            }
Getting both in a test is useless. We'll only receive one of the two. The success in this case.

2022-04-28 11:36 UTC, Moeriki commented
I approved but re-requested a review from @SiteSeerBE.

2022-04-28 11:37 UTC, Moeriki approved these changes

2022-04-28 11:39 UTC, Moeriki commented
A few remarks for future reference

- Don't merge main into your branch. Use rebase.

- Could you use the emojis instead of the placeholders. GitHub seems to render them, but not all clients do. 
![Uploading CleanShot 2022-04-28 at 13.38.48@2x.png…]()

2022-04-28 15:19 UTC, Moeriki approved these changes

2022-04-29 08:08 UTC, SiteSeerBE commented on app/src/fragments.gql
> -}
Wat was er mis met deze methode? De nieuwe methode werkt zo te zien ook, maar geeft `Unknown fragment "BaseErrorFields"` in IDE.

2022-04-29 12:28 UTC, Moeriki commented on app/src/pages/manage/frameworks/[frameworkId]/[competencyId]/create-competency.vue
> +  <template v-else-if="competency?.__typename == 'QueryCompetencySuccess'">
The `competency` var used to be a Competency. Now it is a competency query result. I would update the variables name.

Or maybe better update the `useResult` to again return the competency. I'm not sure doing `__typename` checks in our Vue templates is such a good idea.

2022-05-03 09:38 UTC, Moeriki approved these changes

2022-05-03 09:48 UTC, merged