🥅   add a validation on the `access_token` signature on refresh
OpenSkool/OpenSkool pull request #196
Opened 2022-05-05 12:59 UTC by shkurata

2022-05-05 13:00 UTC, shkurata commented on api/src/api/openid.ts
>        ) {
Maybe this condition can be better written. Any ideas?

2022-05-05 13:01 UTC, shkurata commented on api/src/api/openid.ts
> +      }
The `jwtVerify` method throws an error on invalid signature and that should be enough. We still have the option to add more checks.

2022-05-05 13:02 UTC, shkurata commented
How can this be tested?

2022-05-05 13:23 UTC, Moeriki requested changes

2022-05-05 13:23 UTC, Moeriki commented on api/src/api/openid.ts
> +        await request.server.openId.client.refresh(tokenSet);
We'd probably want to keep the fetched tokenSet in a separate variable until verified. As it is now we store the unvalidated token in the session.

2022-05-05 13:24 UTC, Moeriki commented
Validation needs to happen on the [connect callback](https://github.com/OpenSkool/OpenSkool/blob/main/api/src/api/openid.ts#L84) as well.

2022-05-05 13:28 UTC, shkurata commented on api/src/api/openid.ts
> +      if (request.session.openId.tokenSet.access_token != null) {
Do you mean that we should make an interface for it?

2022-05-05 13:34 UTC, shkurata commented on api/src/api/openid.ts
> +        const JWKS = createRemoteJWKSet(
I have the `app` in order to do that. Any ideas?

2022-05-05 14:33 UTC, Moeriki commented
> How can this be tested?

Manually 😄 the complexity of an OAuth flow is beyond the sensibilities of unit testing and cannot be integration tested.

In good time when we add E2E tests this will be covered well enough.

2022-05-05 15:56 UTC, Moeriki approved these changes

2022-05-05 15:56 UTC, shkurata commented
> Validation needs to happen on the [connect callback](https://github.com/OpenSkool/OpenSkool/blob/main/api/src/api/openid.ts#L84) as well. 

We have there the whole `tokenSet`. Should we do it for every JWT in the set?

2022-05-06 07:48 UTC, closed without merging

2022-05-06 08:48 UTC, Moeriki commented
Manually merged locally.