💄  make the sidenav full height
OpenSkool/OpenSkool pull request #269
Opened 2022-05-18 12:19 UTC by shkurata

Ref: #259

2022-05-18 13:24 UTC, SiteSeerBE requested changes

2022-05-18 13:24 UTC, SiteSeerBE commented on app/src/domain/global/components/layout/main-layout.vue
> +const DESKTOP_MIN_WIDTH = 768;
I'm not sure if a hardcoded value is the way to go.

2022-05-18 13:24 UTC, SiteSeerBE commented on app/src/domain/global/components/layout/main-layout.vue
> +}
Would it be possible to handle this through CSS and existing classes (sm, md, lg,...). This only works onload not on resize.

2022-05-18 13:29 UTC, shkurata commented on app/src/domain/global/components/layout/main-layout.vue
> +}
I couldn't find a way to set up a variable in the controller through the CSS. And also, the acceptance criteria were to check if the user is on a small screen when he loads the app. So, I guess this covers it. I think it would be possible to listen to some screen width change event and update the variable, but this is out of the current scope, I think.

2022-05-18 13:30 UTC, shkurata commented on app/src/domain/global/components/layout/main-layout.vue
> +const DESKTOP_MIN_WIDTH = 768;
I'm open for suggestions.

2022-05-18 14:05 UTC, SiteSeerBE commented on app/src/domain/global/components/layout/main-layout.vue
> +}
class="hidden md:block" would hide the menu on screens below the defined with of "md" and show it on bigger screens. The button would then toggle the class and not the element. So the menu is loaded even if you don't use it. I think for a menu this is acceptable. Let's wait for some input from Dieter.

2022-05-18 14:36 UTC, shkurata commented on app/src/domain/global/components/layout/main-layout.vue
> +}
It will remain hidden with the `hidden` class and the toggle won't work, because we are doing a `transform-x` (just sliding the `nav` to the left).

2022-05-19 12:38 UTC, Moeriki commented on app/src/domain/global/components/layout/main-layout.vue
> +const DESKTOP_MIN_WIDTH = 768;
This should be based on and integrated with windi config. But that's outside of the scope of this ticket.

2022-05-19 13:30 UTC, Moeriki requested changes
There's conflicts. Make sure to rebase.

2022-05-19 13:30 UTC, Moeriki commented on app/src/ui/main-nav/ui-main-nav.vue
> +:global(.ui-title::before) {
This modifies all `.ui-title`. That's not good.

2022-05-19 13:37 UTC, shkurata commented on app/src/ui/main-nav/ui-main-nav-section.vue
> +  <section class="px-5 py-1">
According to MDN, the permitted content of a `nav` element is [flow content](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#flow_content=), which includes the `section` element. It seems semantically correct to me.

2022-05-20 05:45 UTC, SiteSeerBE approved these changes

2022-05-20 10:54 UTC, Moeriki requested changes

2022-05-20 10:54 UTC, Moeriki commented on app/src/ui/main-nav/ui-main-nav.vue
> +        src="data:image/svg+xml;base64,iVBORw0KGgoAAAANSUhEUgAAANwAAADnCAYAAAB15zjvAAAACXBIWXMAAAsTAAALEwEAmpwYAAAgAElEQVR4nO2deZhVxbXoV1Xtc05Pp0eaHoGmsbsBGRpQph4ERcBEg4LzyE3M8NS8+N2b5MbkvWuuSb4MxkRN
Use static asset instead of inlining.

https://vitejs.dev/guide/features.html#static-assets

2022-05-20 11:59 UTC, shkurata commented
Actually, an `ul` cannot contain `div`s and `h1`s and the `ul` is not mandatory in the `nav`,  I think it would be best to get rid of all the `ul/li` shizzle and just use `div`s for the sections and `a`s for the menu items.

2022-05-20 12:13 UTC, Moeriki approved these changes

2022-05-20 12:13 UTC, Moeriki commented on app/src/domain/global/components/layout/main-layout.vue
> +const transitionClasses = 'transition duration-300 ease-in-out transform';
Inadequate `transitionClasses` variable name. The file is `main-layout` so I would assume these classes refer to the main layout while in fact they refer to the navigation. So `navigationTransitionClasses` would be perfect IMO.

2022-05-20 12:13 UTC, Moeriki commented on app/src/domain/global/components/layout/main-layout.vue
> +      <UiMainNav @click="closeSideNavOnMobile">
I'm not sure how this behaves. Any click within the menu closes it?

2022-05-20 12:13 UTC, Moeriki commented on app/src/domain/global/components/layout/main-layout.vue
> +const transitionClasses = 'transition duration-300 ease-in-out transform';
Or maybe `NAVIGATION_TRANSITION_CLASSES` since they're a top-level constant. I'm not sure because it's a bit ugly having this in a template.

2022-05-20 12:28 UTC, shkurata commented on app/src/domain/global/components/layout/main-layout.vue
> +      <UiMainNav @click="closeSideNavOnMobile">
Yes. It is not 100% correct. Maybe a custom event on the `ui-nav-link` would be better.

2022-05-20 12:48 UTC, Moeriki commented on app/src/domain/global/components/layout/main-layout.vue
> +      <UiMainNav @click="closeSideNavOnMobile">
An option is to rename the click handler to something like `handleMainNacClick(event: MouseEvent)`.

We can include `event.target.tagName === 'A'` in the conditional to close on clicks on links.

2022-05-20 12:50 UTC, shkurata commented on app/src/domain/global/components/layout/main-layout.vue
> +      <UiMainNav @click="closeSideNavOnMobile">
```js
router.beforeResolve(() => {
  if (!windowSizeIsMediumOrBigger()) {
    isSideNavOpened.value = false;
  }
});
```

Is that also acceptable?

2022-05-20 13:16 UTC, Moeriki commented on app/src/domain/global/components/layout/main-layout.vue
> +      <UiMainNav @click="closeSideNavOnMobile">
Ahja is best ook wel nice.

2022-05-20 13:34 UTC, merged