Ac rework
OpenSkool/OpenSkool pull request #305
Opened 2022-05-25 09:13 UTC by Moeriki

2022-05-25 11:19 UTC, SiteSeerBE requested changes

2022-05-25 11:19 UTC, SiteSeerBE commented on app/src/vite-types/components.d.ts
> +    UiBreadcrumbItem: typeof import('./../ui/breadcrumb/ui-breadcrumb-item.vue')['default']
`<UiBreadcrumbLink to="">` has not been replaced by `<UiBreadcrumbItem linkTo="">` in components using it.

2022-05-25 13:55 UTC, Moeriki commented on app/src/vite-types/components.d.ts
> +    UiBreadcrumbItem: typeof import('./../ui/breadcrumb/ui-breadcrumb-item.vue')['default']
Fixed.

2022-05-25 16:54 UTC, Moeriki commented on app/src/vite-types/components.d.ts
> +    UiBreadcrumbItem: typeof import('./../ui/breadcrumb/ui-breadcrumb-item.vue')['default']
@SiteSeerBE Ok?

2022-05-27 07:13 UTC, SiteSeerBE commented on app/src/vite-types/components.d.ts
> +    UiBreadcrumbItem: typeof import('./../ui/breadcrumb/ui-breadcrumb-item.vue')['default']
OK

2022-05-27 09:24 UTC, merged