✨  Log out the user when not active
OpenSkool/OpenSkool pull request #334
Opened 2022-06-09 11:39 UTC by shkurata

Ref: #293

2022-06-09 12:51 UTC, moeriki requested changes

2022-06-09 12:51 UTC, moeriki commented on api/src/schema/types/auth.ts
> +          : (expiredAt.getTime() - Date.now()).toString();
You should update the field type to number instead of casting to string.

2022-06-09 12:51 UTC, moeriki commented on app/src/auth.ts
> +    const EXTRA_DELAY = 1000;
Why add an extra delay? I would rather do the opposite. Refresh faster.

2022-06-09 12:51 UTC, moeriki commented on app/src/auth.ts
> +    setSessionExpirationTimer,
Why expose function?

2022-06-09 12:51 UTC, moeriki commented on app/src/auth.ts
> +        setTimeout(() => {
The previous timer should be canceled.

2022-06-09 12:51 UTC, moeriki commented on app/src/auth.ts
> +  function setSessionExpirationTimer(authData: Auth | undefined): void {
The argument is useless as the variable is available in scope. Also why make a function? This could be inline.

2022-06-09 16:39 UTC, moeriki requested changes

2022-06-09 16:39 UTC, moeriki commented on app/src/auth.ts
> +  const timer = ref<NodeJS.Timeout | undefined>();
That's a strange type for a browser environment. Is number possible?

2022-06-09 16:39 UTC, moeriki commented on app/src/auth.ts
> +        const expiresIn = Number(currentUser.tokenSet.refreshToken);
You cast a tokenset to a number? That's probably wrong.

2022-06-09 17:32 UTC, moeriki requested changes
There's a bunch of change in the generated files. Make sure to run `yarn build` and amend the changes again to make sure it's correct.

2022-06-09 17:32 UTC, moeriki commented on app/src/auth.ts
> +        if (!Number.isNaN(expiresIn)) {
Isn't `currentUser.tokenSet.refreshToken.expiresIn` already a number? I think the cast and `NaN` check is not necessary.

2022-06-09 17:32 UTC, moeriki commented on app/src/auth.ts
> +          }
`if` condition isn't necessary. `clearTimeout` can take `number | undefined` anyways.

2022-06-09 17:32 UTC, moeriki commented on app/src/auth.ts
> +          timer.value = window.setTimeout(refresh, expiresIn);
The ESLint disable isn't really necessary. Better to do `() => void refresh()`.

`void` is a convenient way to communicate in code that a function result can be discarded.

2022-06-09 17:56 UTC, shkurata commented
> `if` condition isn't necessary. `clearTimeout` can take `number | undefined` anyways. 

I had to leave the `null` check because I get errors.

2022-06-10 08:14 UTC, moeriki approved these changes

2022-06-10 08:15 UTC, merged